Exploratory notebook to check parcellation data and test parcellation-related functions

In [1]:
import cf_parcellation 
# parcels_indices = [21, 24, 25, 22, 23]
parcel_names = ["Anterior Cingulate and Medial Prefrontal Cortex",
                 "Inferior Dorso-Lateral Prefrontal Cortex",
                 "Superior Dorso-Lateral Prefrontal Cortex",
                 "Orbital and Polar Frontal Cortex",
                 "Inferior Frontal Cortex",
                 ]
# parcels_indices = cf_parcellation.get_parcel_idx_with_names_2hemi(parcel_names)
parcel_names = cf_parcellation.get_parcel_names_2hemi(parcel_names)
print("parcel_names", parcel_names)
parcels_indices = cf_parcellation.get_parcel_idx_with_names(parcel_names)
print("parcel_indices", parcels_indices)
n_parcels = len(parcels_indices)

parcel_names ['Anterior Cingulate and Medial Prefrontal Cortex_rh', 'Anterior Cingulate and Medial Prefrontal Cortex_lh', 'Inferior Dorso-Lateral Prefrontal Cortex_rh', 'Inferior Dorso-Lateral Prefrontal Cortex_lh', 'Superior Dorso-Lateral Prefrontal Cortex_rh', 'Superior Dorso-Lateral Prefrontal Cortex_lh', 'Orbital and Polar Frontal Cortex_rh', 'Orbital and Polar Frontal Cortex_lh', 'Inferior Frontal Cortex_rh', 'Inferior Frontal Cortex_lh']
parcel_indices [21, 47, 24, 50, 25, 51, 22, 48, 23, 49]


In [ ]:
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import nilearn
import osl
import osl.source_recon.parcellation as parcellation

parcellation_filenames = [
    # "fMRI_parcellation_ds2mm.nii.gz",
    # "aal_cortical_merged_8mm_stacked.nii.gz",
    # "dk_cortical.nii.gz",
    # "dk_full.nii.gz",
    # "fmri_d100_parcellation_with_PCC_reduced_2mm_ss5mm_ds8mm.nii.gz",
    # "fmri_d100_parcellation_with_PCC_reduced_2mm.nii.gz",
    # "fmri_d100_parcellation_with_PCC_tighterMay15_v2_2mm.nii.gz",
    # "fmri_d100_parcellation_with_PCC_tighterMay15_v2_6mm_exclusive.nii.gz",
    # "fmri_d100_parcellation_with_PCC_tighterMay15_v2_8mm.nii.gz",
    # "fMRI_parcellation_ds8mm.nii.gz",
    # "giles_39_binary.nii.gz",
    # "Glasser50_space-MNI152NLin6_res-8x8x8.nii.gz",
    # "Glasser52_binary_space-MNI152NLin6_res-8x8x8.nii.gz",
    "parcellation/glasser52/Glasser52_binary_space-MNI152NLin6_res-1x1x1.nii.gz",
    "parcellation/glasser52/Glasser52_binary_space-MNI152NLin6_res-2x2x2.nii.gz",
    "parcellation/glasser52/Glasser52_binary_space-MNI152NLin6_res-8x8x8.nii.gz",
    # "HarvardOxford-sub-prob-bin-2mm.nii.gz",
    # "HarvOxf-sub-Schaefer100-combined-2mm_4d_ds8.nii.gz",
    # "HarvOxf-sub-Schaefer100-combined-2mm_4d.nii.gz",
    # "HarvOxf-sub-Schaefer100-combined-2mm.nii.gz",
    # "MNI152_T1_2mm_brain.nii.gz",
    # "MNI152_T1_8mm_brain.nii.gz",
    # "reduced_hcp-mmp_2mm.nii.gz",
    # "reduced_hcp-mmp_8mm.nii.gz",
    # "Schaefer2018_100Parcels_7Networks_order_FSLMNI152_2mm_4d_ds8.nii.gz",
    # "Schaefer2018_100Parcels_7Networks_order_FSLMNI152_2mm_4d.nii.gz",
    # "Schaefer2018_100Parcels_7Networks_order_FSLMNI152_2mm.nii.gz",
    # "WTA_fMRI_parcellation_ds2mm.nii.gz",
    # "WTA_fMRI_parcellation_ds8mm.nii.gz",
]

highlight_color = mpl.cm.get_cmap("Set1")(4)
cmap_roi = mpl.colors.LinearSegmentedColormap.from_list("Highlight", [(0, 0, 0), highlight_color])

for fname in parcellation_filenames:
    print(fname)
    parcel_centers = parcellation.parcel_centers(fname)
    print(f"Number of parcels: {parcel_centers.shape[0]}")
    i_example_parcel = 21 # 21, 47
    print(f"MNI center coordinates for parcel {i_example_parcel}: {parcel_centers[i_example_parcel]}")
    # display = parcellation.plot_parcellation(fname, title=fname)
    fpath = parcellation.find_file(fname)
    # display = nilearn.plotting.plot_prob_atlas(fpath, title=fname)
    # display = nilearn.plotting.plot_prob_atlas(fpath, title=fname, colorbar=True)
    # for i_parcel in [21]:
    #     display = nilearn.plotting.plot_prob_atlas(fpath, title=f"cut on parcel {i_parcel+1} center", view_type="filled_contours", display_mode="ortho",
    #                                                cut_coords=parcel_centers[i_parcel], colorbar=True)


    for i_parcel in [21]: #24, 25]:#, 47,, 6, 32, 16, 42, 15, 41, 19, 45]:
        parcel_img = nilearn.image.index_img(fpath, i_parcel)
        parcel_img_data = parcel_img.get_fdata()
        print(parcel_img_data.shape, parcel_img_data.min(), parcel_img_data.max())
        binary_parcel_img = nilearn.image.binarize_img(parcel_img, threshold=0.25)
        binary_parcel_img_data = binary_parcel_img.get_fdata()
        print(binary_parcel_img_data.shape, binary_parcel_img_data.min(), binary_parcel_img_data.max())
        display = nilearn.plotting.plot_roi(binary_parcel_img, title=f"parcel #{i_parcel+1}", cmap=cmap_roi, vmin=0)
        # display = nilearn.plotting.plot_roi(binary_parcel_img, title=f"parcel #{i_parcel+1}", cmap="viridis", vmin=0)
        # display = nilearn.plotting.plot_roi(parcel_img, title=f"parcel #{i_parcel+1}", cmap="viridis", vmin=0, vmax=1)
    
    # parcel_values = [(i+1) / n_parcels for i in range(n_parcels)]
    parcel_values = [i+1 for i in range(n_parcels)]
    # parcels_cmap =  mpl.colors.LinearSegmentedColormap.from_list("Parcels", [(0, (0,0,0))] + [(parcel_values[i], mpl.cm.get_cmap("Set1")(i)) for i in range(n_parcels)])
    fst_parcel_img = nilearn.image.index_img(fpath, parcels_indices[0])
    fst_parcel_data = fst_parcel_img.get_fdata()
    parcels_img_data = np.zeros_like(fst_parcel_data)
    for i_parcel, idx in enumerate(parcels_indices):
        parcel_img = nilearn.image.index_img(fpath, idx)
        parcels_img_data[parcel_img.get_fdata() > 1e-6] = parcel_values[i_parcel]
    parcels_img = nilearn.image.new_img_like(fst_parcel_img, parcels_img_data)
    print(parcels_img)
    print(parcel_values)
    print(parcels_img_data.min())
    print(parcels_img_data.max())
    # display = nilearn.plotting.plot_roi(parcels_img, title="selected parcels")
    # display = nilearn.plotting.plot_roi(parcels_img, title="selected parcels", cmap=parcels_cmap, threshold=1e-6, vmin=0, colorbar=True)
    # display = nilearn.plotting.plot_roi(parcels_img, title="selected parcels", cmap="Set1", threshold=1e-6, vmin=1, vmax=10, cbar_vmin=1, cbar_vmax=n_parcels+1, colorbar=True)
    display = nilearn.plotting.plot_roi(parcels_img, title="selected parcels", cmap="Set1", threshold=1e-6, vmin=1, vmax=10, colorbar=False)
    
    # display = nilearn.plotting.plot_prob_atlas(fpath, title=fname, view_type="filled_contours")

/var/folders/0p/8mwmxvqj3tz9f07rkk72z0y00000gn/T/ipykernel_9190/2841619625.py:40: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed two minor releases later. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap(obj)`` instead.
  highlight_color = mpl.cm.get_cmap("Set1")(4)


parcellation/glasser52/Glasser52_binary_space-MNI152NLin6_res-1x1x1.nii.gz
Number of parcels: 52
MNI center coordinates for parcel 21: [ 4.63161132 33.71094711 14.36749413]
(182, 218, 182) 0.0 1.0
(182, 218, 182) 0.0 1.0


/opt/anaconda3/envs/osl/lib/python3.8/site-packages/nilearn/image/image.py:1066: UserWarning: Data array used to create a new image contains 64-bit ints. This is likely due to creating the array with numpy and passing `int` as the `dtype`. Many tools such as FSL and SPM cannot deal with int64 in Nifti images, so for compatibility the data has been converted to int32.
  return new_img_like(niimg, result, niimg.affine)



<class 'nibabel.nifti1.Nifti1Image'>
data shape (182, 218, 182)
affine:
[[  -1.    0.    0.   90.]
 [   0.    1.    0. -126.]
 [   0.    0.    1.  -72.]
 [   0.    0.    0.    1.]]
metadata:
<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b''
dim_info        : 0
dim             : [  3 182 218 182   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : float64
bitpix          : 64
slice_start     : 0
pixdim          : [-1.  1.  1.  1.  1.  1.  1.  1.]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 0
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b''
aux_file        : b''
qform_code      : unknown
sform_code   

/opt/anaconda3/envs/osl/lib/python3.8/site-packages/nilearn/image/image.py:1066: UserWarning: Data array used to create a new image contains 64-bit ints. This is likely due to creating the array with numpy and passing `int` as the `dtype`. Many tools such as FSL and SPM cannot deal with int64 in Nifti images, so for compatibility the data has been converted to int32.
  return new_img_like(niimg, result, niimg.affine)
